# TCL File Generated by Component Editor 25.1
# Wed Apr 22 13:30:09 CDT 2026
# DO NOT MODIFY


# 
# gpio_axi4lite "GPIO - AXI4Lite" v1.0
# Eder Torres 2026.04.22.13:30:09
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module gpio_axi4lite
# 
set_module_property DESCRIPTION ""
set_module_property NAME gpio_axi4lite
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Eder Torres"
set_module_property DISPLAY_NAME "GPIO - AXI4Lite"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL axi_lite_gpio
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file axi_lite_gpio.sv SYSTEM_VERILOG PATH ../rtl/peripherals/gpio/axi_lite_gpio.sv TOP_LEVEL_FILE
add_fileset_file gpio_regs.sv SYSTEM_VERILOG PATH ../rtl/peripherals/gpio/regs/gpio_regs.sv


# 
# parameters
# 
add_parameter ADDR_W INTEGER 12 ""
set_parameter_property ADDR_W DEFAULT_VALUE 12
set_parameter_property ADDR_W DISPLAY_NAME ADDR_W
set_parameter_property ADDR_W WIDTH ""
set_parameter_property ADDR_W TYPE INTEGER
set_parameter_property ADDR_W UNITS None
set_parameter_property ADDR_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_W DESCRIPTION ""
set_parameter_property ADDR_W HDL_PARAMETER true
add_parameter DATA_W INTEGER 32 ""
set_parameter_property DATA_W DEFAULT_VALUE 32
set_parameter_property DATA_W DISPLAY_NAME DATA_W
set_parameter_property DATA_W WIDTH ""
set_parameter_property DATA_W TYPE INTEGER
set_parameter_property DATA_W UNITS None
set_parameter_property DATA_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_W DESCRIPTION ""
set_parameter_property DATA_W HDL_PARAMETER true
add_parameter GPIO_W INTEGER 32 ""
set_parameter_property GPIO_W DEFAULT_VALUE 32
set_parameter_property GPIO_W DISPLAY_NAME GPIO_W
set_parameter_property GPIO_W WIDTH ""
set_parameter_property GPIO_W TYPE INTEGER
set_parameter_property GPIO_W UNITS None
set_parameter_property GPIO_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property GPIO_W DESCRIPTION ""
set_parameter_property GPIO_W HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst_n reset_n Input 1


# 
# connection point s_axil
# 
add_interface s_axil axi4lite end
set_interface_property s_axil associatedClock clock
set_interface_property s_axil associatedReset reset
set_interface_property s_axil readAcceptanceCapability 1
set_interface_property s_axil writeAcceptanceCapability 1
set_interface_property s_axil combinedAcceptanceCapability 1
set_interface_property s_axil readDataReorderingDepth 1
set_interface_property s_axil bridgesToMaster ""
set_interface_property s_axil ENABLED true
set_interface_property s_axil EXPORT_OF ""
set_interface_property s_axil PORT_NAME_MAP ""
set_interface_property s_axil CMSIS_SVD_VARIABLES ""
set_interface_property s_axil SVD_ADDRESS_GROUP ""

add_interface_port s_axil s_axil_araddr araddr Input ADDR_W
add_interface_port s_axil s_axil_arready arready Output 1
add_interface_port s_axil s_axil_arvalid arvalid Input 1
add_interface_port s_axil s_axil_awaddr awaddr Input ADDR_W
add_interface_port s_axil s_axil_wvalid wvalid Input 1
add_interface_port s_axil s_axil_wstrb wstrb Input 4
add_interface_port s_axil s_axil_wready wready Output 1
add_interface_port s_axil s_axil_wdata wdata Input 32
add_interface_port s_axil s_axil_rvalid rvalid Output 1
add_interface_port s_axil s_axil_rresp rresp Output 2
add_interface_port s_axil s_axil_rready rready Input 1
add_interface_port s_axil s_axil_rdata rdata Output 32
add_interface_port s_axil s_axil_bvalid bvalid Output 1
add_interface_port s_axil s_axil_bresp bresp Output 2
add_interface_port s_axil s_axil_bready bready Input 1
add_interface_port s_axil s_axil_awvalid awvalid Input 1
add_interface_port s_axil s_axil_awready awready Output 1


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint ""
set_interface_property irq associatedClock clock
set_interface_property irq associatedReset reset
set_interface_property irq bridgedReceiverOffset ""
set_interface_property irq bridgesToReceiver ""
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq irq_o irq Output 1


# 
# connection point gpio
# 
add_interface gpio conduit end
set_interface_property gpio associatedClock clock
set_interface_property gpio associatedReset ""
set_interface_property gpio ENABLED true
set_interface_property gpio EXPORT_OF ""
set_interface_property gpio PORT_NAME_MAP ""
set_interface_property gpio CMSIS_SVD_VARIABLES ""
set_interface_property gpio SVD_ADDRESS_GROUP ""

add_interface_port gpio gpio_in_i gpio_in Input GPIO_W
add_interface_port gpio gpio_out_o gpio_out Output GPIO_W
add_interface_port gpio gpio_oe_o gpio_oe Output GPIO_W

