# TCL File Generated by Component Editor 25.1
# Mon Apr 20 01:56:58 CDT 2026
# DO NOT MODIFY


# 
# i2c_master "I2C Master Simple - AXI4Lite" v1.0
# Eder Torres 2026.04.20.01:56:58
# I2C core - no FIFO, no multimaster, no clock stretching, tristate buffer are to be setup on the top-level
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module i2c_master
# 
set_module_property DESCRIPTION "I2C core - no FIFO, no multimaster, no clock stretching, tristate buffer are to be setup on the top-level"
set_module_property NAME i2c_master
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Eder Torres"
set_module_property DISPLAY_NAME "I2C Master Simple - AXI4Lite"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL axi_lite_i2c
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file axi_lite_i2c.sv SYSTEM_VERILOG PATH ../rtl/peripherals/i2c/axi_lite_i2c.sv TOP_LEVEL_FILE
add_fileset_file i2c_regs.sv SYSTEM_VERILOG PATH ../rtl/peripherals/i2c/regs/i2c_regs.sv
add_fileset_file i2c_master_core.sv SYSTEM_VERILOG PATH ../rtl/peripherals/i2c/core/i2c_master_core.sv


# 
# parameters
# 
add_parameter ADDR_W INTEGER 12 ""
set_parameter_property ADDR_W DEFAULT_VALUE 12
set_parameter_property ADDR_W DISPLAY_NAME ADDR_W
set_parameter_property ADDR_W WIDTH ""
set_parameter_property ADDR_W TYPE INTEGER
set_parameter_property ADDR_W UNITS None
set_parameter_property ADDR_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_W DESCRIPTION ""
set_parameter_property ADDR_W HDL_PARAMETER true
add_parameter DATA_W INTEGER 32 ""
set_parameter_property DATA_W DEFAULT_VALUE 32
set_parameter_property DATA_W DISPLAY_NAME DATA_W
set_parameter_property DATA_W WIDTH ""
set_parameter_property DATA_W TYPE INTEGER
set_parameter_property DATA_W UNITS None
set_parameter_property DATA_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_W DESCRIPTION ""
set_parameter_property DATA_W HDL_PARAMETER true
add_parameter BYTE_W INTEGER 8 ""
set_parameter_property BYTE_W DEFAULT_VALUE 8
set_parameter_property BYTE_W DISPLAY_NAME BYTE_W
set_parameter_property BYTE_W WIDTH ""
set_parameter_property BYTE_W TYPE INTEGER
set_parameter_property BYTE_W UNITS None
set_parameter_property BYTE_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BYTE_W DESCRIPTION ""
set_parameter_property BYTE_W HDL_PARAMETER true
add_parameter CMD_W INTEGER 3 ""
set_parameter_property CMD_W DEFAULT_VALUE 3
set_parameter_property CMD_W DISPLAY_NAME CMD_W
set_parameter_property CMD_W WIDTH ""
set_parameter_property CMD_W TYPE INTEGER
set_parameter_property CMD_W UNITS None
set_parameter_property CMD_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CMD_W DESCRIPTION ""
set_parameter_property CMD_W HDL_PARAMETER true
add_parameter DIVISOR_W INTEGER 16 ""
set_parameter_property DIVISOR_W DEFAULT_VALUE 16
set_parameter_property DIVISOR_W DISPLAY_NAME DIVISOR_W
set_parameter_property DIVISOR_W WIDTH ""
set_parameter_property DIVISOR_W TYPE INTEGER
set_parameter_property DIVISOR_W UNITS None
set_parameter_property DIVISOR_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DIVISOR_W DESCRIPTION ""
set_parameter_property DIVISOR_W HDL_PARAMETER true
add_parameter MIN_DIVISOR INTEGER 1 ""
set_parameter_property MIN_DIVISOR DEFAULT_VALUE 1
set_parameter_property MIN_DIVISOR DISPLAY_NAME MIN_DIVISOR
set_parameter_property MIN_DIVISOR WIDTH ""
set_parameter_property MIN_DIVISOR TYPE INTEGER
set_parameter_property MIN_DIVISOR UNITS None
set_parameter_property MIN_DIVISOR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MIN_DIVISOR DESCRIPTION ""
set_parameter_property MIN_DIVISOR HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst_n reset_n Input 1


# 
# connection point s_axil
# 
add_interface s_axil axi4lite end
set_interface_property s_axil associatedClock clock
set_interface_property s_axil associatedReset reset
set_interface_property s_axil readAcceptanceCapability 1
set_interface_property s_axil writeAcceptanceCapability 1
set_interface_property s_axil combinedAcceptanceCapability 1
set_interface_property s_axil readDataReorderingDepth 1
set_interface_property s_axil bridgesToMaster ""
set_interface_property s_axil ENABLED true
set_interface_property s_axil EXPORT_OF ""
set_interface_property s_axil PORT_NAME_MAP ""
set_interface_property s_axil CMSIS_SVD_VARIABLES ""
set_interface_property s_axil SVD_ADDRESS_GROUP ""

add_interface_port s_axil s_axil_araddr araddr Input ADDR_W
add_interface_port s_axil s_axil_arready arready Output 1
add_interface_port s_axil s_axil_arvalid arvalid Input 1
add_interface_port s_axil s_axil_awaddr awaddr Input ADDR_W
add_interface_port s_axil s_axil_wvalid wvalid Input 1
add_interface_port s_axil s_axil_wstrb wstrb Input 4
add_interface_port s_axil s_axil_wready wready Output 1
add_interface_port s_axil s_axil_wdata wdata Input 32
add_interface_port s_axil s_axil_rvalid rvalid Output 1
add_interface_port s_axil s_axil_rresp rresp Output 2
add_interface_port s_axil s_axil_rready rready Input 1
add_interface_port s_axil s_axil_rdata rdata Output 32
add_interface_port s_axil s_axil_bvalid bvalid Output 1
add_interface_port s_axil s_axil_bresp bresp Output 2
add_interface_port s_axil s_axil_bready bready Input 1
add_interface_port s_axil s_axil_awvalid awvalid Input 1
add_interface_port s_axil s_axil_awready awready Output 1


# 
# connection point I2C_Master
# 
add_interface I2C_Master conduit end
set_interface_property I2C_Master associatedClock clock
set_interface_property I2C_Master associatedReset ""
set_interface_property I2C_Master ENABLED true
set_interface_property I2C_Master EXPORT_OF ""
set_interface_property I2C_Master PORT_NAME_MAP ""
set_interface_property I2C_Master CMSIS_SVD_VARIABLES ""
set_interface_property I2C_Master SVD_ADDRESS_GROUP ""

add_interface_port I2C_Master i2c_sda_in sda_in Input 1
add_interface_port I2C_Master i2c_sda_out sda_out Output 1
add_interface_port I2C_Master i2c_scl_in scl_in Input 1
add_interface_port I2C_Master i2c_scl_out scl_out Output 1
add_interface_port I2C_Master i2c_master_receiving master_receiving_o Output 1

