# TCL File Generated by Component Editor 25.1
# Tue Apr 14 23:55:39 CDT 2026
# DO NOT MODIFY


# 
# pwm_hbridge_axi4lite "PWM Multichannel - H-Bridge - AXI4 Lite" v3
# Eder Torres 2026.04.14.23:55:39
# PWM for motor control up to 32 channels. it interfaces with h-bridges with in1, in2, and pwm inputs. 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pwm_hbridge_axi4lite
# 
set_module_property DESCRIPTION "PWM for motor control up to 32 channels. it interfaces with h-bridges with in1, in2, and pwm inputs. "
set_module_property NAME pwm_hbridge_axi4lite
set_module_property VERSION 3
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Eder Torres"
set_module_property DISPLAY_NAME "PWM Multichannel - H-Bridge - AXI4 Lite"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL axi_lite_pwm_motor
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file axi_lite_pwm_motor.sv SYSTEM_VERILOG PATH ../rtl/peripherals/pwm/axi_lite_pwm_motor.sv TOP_LEVEL_FILE
add_fileset_file pwm_hbridge_adapter.sv SYSTEM_VERILOG PATH ../rtl/peripherals/pwm/adapters/pwm_hbridge_adapter.sv
add_fileset_file pwm_compare.sv SYSTEM_VERILOG PATH ../rtl/peripherals/pwm/core/pwm_compare.sv
add_fileset_file pwm_core_ip.sv SYSTEM_VERILOG PATH ../rtl/peripherals/pwm/core/pwm_core_ip.sv
add_fileset_file pwm_timebase.sv SYSTEM_VERILOG PATH ../rtl/peripherals/pwm/core/pwm_timebase.sv
add_fileset_file pwm_regs_hbridge_ext.sv SYSTEM_VERILOG PATH ../rtl/peripherals/pwm/regs/pwm_regs_hbridge_ext.sv
add_fileset_file pwm_subsystem_motor.sv SYSTEM_VERILOG PATH ../rtl/peripherals/pwm/subsystems/pwm_subsystem_motor.sv
add_fileset_file pwm_regs_common.sv SYSTEM_VERILOG PATH ../rtl/peripherals/pwm/regs/pwm_regs_common.sv


# 
# parameters
# 
add_parameter AXI_ADDR_W INTEGER 12 ""
set_parameter_property AXI_ADDR_W DEFAULT_VALUE 12
set_parameter_property AXI_ADDR_W DISPLAY_NAME AXI_ADDR_W
set_parameter_property AXI_ADDR_W WIDTH ""
set_parameter_property AXI_ADDR_W TYPE INTEGER
set_parameter_property AXI_ADDR_W UNITS None
set_parameter_property AXI_ADDR_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXI_ADDR_W DESCRIPTION ""
set_parameter_property AXI_ADDR_W HDL_PARAMETER true
add_parameter AXI_DATA_W INTEGER 32 ""
set_parameter_property AXI_DATA_W DEFAULT_VALUE 32
set_parameter_property AXI_DATA_W DISPLAY_NAME AXI_DATA_W
set_parameter_property AXI_DATA_W WIDTH ""
set_parameter_property AXI_DATA_W TYPE INTEGER
set_parameter_property AXI_DATA_W UNITS None
set_parameter_property AXI_DATA_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXI_DATA_W DESCRIPTION ""
set_parameter_property AXI_DATA_W HDL_PARAMETER true
add_parameter CNT_W INTEGER 32 ""
set_parameter_property CNT_W DEFAULT_VALUE 32
set_parameter_property CNT_W DISPLAY_NAME CNT_W
set_parameter_property CNT_W WIDTH ""
set_parameter_property CNT_W TYPE INTEGER
set_parameter_property CNT_W UNITS None
set_parameter_property CNT_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CNT_W DESCRIPTION ""
set_parameter_property CNT_W HDL_PARAMETER true
add_parameter CHANNELS INTEGER 4 ""
set_parameter_property CHANNELS DEFAULT_VALUE 4
set_parameter_property CHANNELS DISPLAY_NAME CHANNELS
set_parameter_property CHANNELS WIDTH ""
set_parameter_property CHANNELS TYPE INTEGER
set_parameter_property CHANNELS UNITS None
set_parameter_property CHANNELS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CHANNELS DESCRIPTION ""
set_parameter_property CHANNELS HDL_PARAMETER true
add_parameter APPLY_ON_PERIOD_END BOOLEAN true ""
set_parameter_property APPLY_ON_PERIOD_END DEFAULT_VALUE true
set_parameter_property APPLY_ON_PERIOD_END DISPLAY_NAME APPLY_ON_PERIOD_END
set_parameter_property APPLY_ON_PERIOD_END WIDTH ""
set_parameter_property APPLY_ON_PERIOD_END TYPE BOOLEAN
set_parameter_property APPLY_ON_PERIOD_END UNITS None
set_parameter_property APPLY_ON_PERIOD_END DESCRIPTION ""
set_parameter_property APPLY_ON_PERIOD_END HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst_n reset_n Input 1


# 
# connection point s_axil
# 
add_interface s_axil axi4lite end
set_interface_property s_axil associatedClock clock
set_interface_property s_axil associatedReset reset
set_interface_property s_axil readAcceptanceCapability 1
set_interface_property s_axil writeAcceptanceCapability 1
set_interface_property s_axil combinedAcceptanceCapability 1
set_interface_property s_axil readDataReorderingDepth 1
set_interface_property s_axil bridgesToMaster ""
set_interface_property s_axil ENABLED true
set_interface_property s_axil EXPORT_OF ""
set_interface_property s_axil PORT_NAME_MAP ""
set_interface_property s_axil CMSIS_SVD_VARIABLES ""
set_interface_property s_axil SVD_ADDRESS_GROUP ""

add_interface_port s_axil s_axil_araddr araddr Input AXI_ADDR_W
add_interface_port s_axil s_axil_arready arready Output 1
add_interface_port s_axil s_axil_arvalid arvalid Input 1
add_interface_port s_axil s_axil_awaddr awaddr Input AXI_ADDR_W
add_interface_port s_axil s_axil_wvalid wvalid Input 1
add_interface_port s_axil s_axil_wstrb wstrb Input 4
add_interface_port s_axil s_axil_wready wready Output 1
add_interface_port s_axil s_axil_wdata wdata Input 32
add_interface_port s_axil s_axil_rvalid rvalid Output 1
add_interface_port s_axil s_axil_rresp rresp Output 2
add_interface_port s_axil s_axil_rready rready Input 1
add_interface_port s_axil s_axil_rdata rdata Output 32
add_interface_port s_axil s_axil_bvalid bvalid Output 1
add_interface_port s_axil s_axil_bresp bresp Output 2
add_interface_port s_axil s_axil_bready bready Input 1
add_interface_port s_axil s_axil_awvalid awvalid Input 1
add_interface_port s_axil s_axil_awready awready Output 1


# 
# connection point pwm_hbridge
# 
add_interface pwm_hbridge conduit end
set_interface_property pwm_hbridge associatedClock clock
set_interface_property pwm_hbridge associatedReset ""
set_interface_property pwm_hbridge ENABLED true
set_interface_property pwm_hbridge EXPORT_OF ""
set_interface_property pwm_hbridge PORT_NAME_MAP ""
set_interface_property pwm_hbridge CMSIS_SVD_VARIABLES ""
set_interface_property pwm_hbridge SVD_ADDRESS_GROUP ""

add_interface_port pwm_hbridge pwm_o pwm Output CHANNELS
add_interface_port pwm_hbridge in1_o in1 Output CHANNELS
add_interface_port pwm_hbridge in2_o in2 Output CHANNELS

