# TCL File Generated by Component Editor 25.1
# Tue Apr 21 17:57:48 CDT 2026
# DO NOT MODIFY


# 
# Seg7_debug "Seven Segment display" v1.0
# Eder Torres 2026.04.21.17:57:48
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Seg7_debug
# 
set_module_property DESCRIPTION ""
set_module_property NAME Seg7_debug
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Eder Torres"
set_module_property DISPLAY_NAME "Seven Segment display"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL axil_lite_seg7_debug
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file axil_lite_seg7_debug.sv SYSTEM_VERILOG PATH ../rtl/peripherals/debug/axil_lite_seg7_debug.sv TOP_LEVEL_FILE
add_fileset_file seg7_debug_core.sv SYSTEM_VERILOG PATH ../rtl/peripherals/debug/core/seg7_debug_core.sv
add_fileset_file seg7_debug_regs.sv SYSTEM_VERILOG PATH ../rtl/peripherals/debug/regs/seg7_debug_regs.sv


# 
# parameters
# 
add_parameter ADDR_W INTEGER 12 ""
set_parameter_property ADDR_W DEFAULT_VALUE 12
set_parameter_property ADDR_W DISPLAY_NAME ADDR_W
set_parameter_property ADDR_W WIDTH ""
set_parameter_property ADDR_W TYPE INTEGER
set_parameter_property ADDR_W UNITS None
set_parameter_property ADDR_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_W DESCRIPTION ""
set_parameter_property ADDR_W HDL_PARAMETER true
add_parameter DATA_W INTEGER 32 ""
set_parameter_property DATA_W DEFAULT_VALUE 32
set_parameter_property DATA_W DISPLAY_NAME DATA_W
set_parameter_property DATA_W WIDTH ""
set_parameter_property DATA_W TYPE INTEGER
set_parameter_property DATA_W UNITS None
set_parameter_property DATA_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_W DESCRIPTION ""
set_parameter_property DATA_W HDL_PARAMETER true
add_parameter NUM_DIGITS INTEGER 6 ""
set_parameter_property NUM_DIGITS DEFAULT_VALUE 6
set_parameter_property NUM_DIGITS DISPLAY_NAME NUM_DIGITS
set_parameter_property NUM_DIGITS WIDTH ""
set_parameter_property NUM_DIGITS TYPE INTEGER
set_parameter_property NUM_DIGITS UNITS None
set_parameter_property NUM_DIGITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NUM_DIGITS DESCRIPTION ""
set_parameter_property NUM_DIGITS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point s_axil
# 
add_interface s_axil axi4lite end
set_interface_property s_axil associatedClock clock
set_interface_property s_axil associatedReset reset
set_interface_property s_axil readAcceptanceCapability 1
set_interface_property s_axil writeAcceptanceCapability 1
set_interface_property s_axil combinedAcceptanceCapability 1
set_interface_property s_axil readDataReorderingDepth 1
set_interface_property s_axil bridgesToMaster ""
set_interface_property s_axil ENABLED true
set_interface_property s_axil EXPORT_OF ""
set_interface_property s_axil PORT_NAME_MAP ""
set_interface_property s_axil CMSIS_SVD_VARIABLES ""
set_interface_property s_axil SVD_ADDRESS_GROUP ""

add_interface_port s_axil s_axil_araddr araddr Input "((ADDR_W-1)) - (0) + 1"
add_interface_port s_axil s_axil_arready arready Output 1
add_interface_port s_axil s_axil_arvalid arvalid Input 1
add_interface_port s_axil s_axil_awaddr awaddr Input "((ADDR_W-1)) - (0) + 1"
add_interface_port s_axil s_axil_wvalid wvalid Input 1
add_interface_port s_axil s_axil_wstrb wstrb Input "(((DATA_W/8)-1)) - (0) + 1"
add_interface_port s_axil s_axil_wready wready Output 1
add_interface_port s_axil s_axil_wdata wdata Input "((DATA_W-1)) - (0) + 1"
add_interface_port s_axil s_axil_rvalid rvalid Output 1
add_interface_port s_axil s_axil_rresp rresp Output 2
add_interface_port s_axil s_axil_rready rready Input 1
add_interface_port s_axil s_axil_rdata rdata Output "((DATA_W-1)) - (0) + 1"
add_interface_port s_axil s_axil_bvalid bvalid Output 1
add_interface_port s_axil s_axil_bresp bresp Output 2
add_interface_port s_axil s_axil_bready bready Input 1
add_interface_port s_axil s_axil_awvalid awvalid Input 1
add_interface_port s_axil s_axil_awready awready Output 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst_n reset_n Input 1


# 
# connection point HEX0
# 
add_interface HEX0 conduit end
set_interface_property HEX0 associatedClock clock
set_interface_property HEX0 associatedReset ""
set_interface_property HEX0 ENABLED true
set_interface_property HEX0 EXPORT_OF ""
set_interface_property HEX0 PORT_NAME_MAP ""
set_interface_property HEX0 CMSIS_SVD_VARIABLES ""
set_interface_property HEX0 SVD_ADDRESS_GROUP ""

add_interface_port HEX0 hex0_o hex0 Output 8


# 
# connection point HEX1
# 
add_interface HEX1 conduit end
set_interface_property HEX1 associatedClock clock
set_interface_property HEX1 associatedReset ""
set_interface_property HEX1 ENABLED true
set_interface_property HEX1 EXPORT_OF ""
set_interface_property HEX1 PORT_NAME_MAP ""
set_interface_property HEX1 CMSIS_SVD_VARIABLES ""
set_interface_property HEX1 SVD_ADDRESS_GROUP ""

add_interface_port HEX1 hex1_o hex1 Output 8


# 
# connection point HEX2
# 
add_interface HEX2 conduit end
set_interface_property HEX2 associatedClock clock
set_interface_property HEX2 associatedReset ""
set_interface_property HEX2 ENABLED true
set_interface_property HEX2 EXPORT_OF ""
set_interface_property HEX2 PORT_NAME_MAP ""
set_interface_property HEX2 CMSIS_SVD_VARIABLES ""
set_interface_property HEX2 SVD_ADDRESS_GROUP ""

add_interface_port HEX2 hex2_o hex2 Output 8


# 
# connection point HEX3
# 
add_interface HEX3 conduit end
set_interface_property HEX3 associatedClock clock
set_interface_property HEX3 associatedReset ""
set_interface_property HEX3 ENABLED true
set_interface_property HEX3 EXPORT_OF ""
set_interface_property HEX3 PORT_NAME_MAP ""
set_interface_property HEX3 CMSIS_SVD_VARIABLES ""
set_interface_property HEX3 SVD_ADDRESS_GROUP ""

add_interface_port HEX3 hex3_o hex3 Output 8


# 
# connection point HEX4
# 
add_interface HEX4 conduit end
set_interface_property HEX4 associatedClock clock
set_interface_property HEX4 associatedReset ""
set_interface_property HEX4 ENABLED true
set_interface_property HEX4 EXPORT_OF ""
set_interface_property HEX4 PORT_NAME_MAP ""
set_interface_property HEX4 CMSIS_SVD_VARIABLES ""
set_interface_property HEX4 SVD_ADDRESS_GROUP ""

add_interface_port HEX4 hex4_o hex4 Output 8


# 
# connection point HEX5
# 
add_interface HEX5 conduit end
set_interface_property HEX5 associatedClock clock
set_interface_property HEX5 associatedReset ""
set_interface_property HEX5 ENABLED true
set_interface_property HEX5 EXPORT_OF ""
set_interface_property HEX5 PORT_NAME_MAP ""
set_interface_property HEX5 CMSIS_SVD_VARIABLES ""
set_interface_property HEX5 SVD_ADDRESS_GROUP ""

add_interface_port HEX5 hex5_o hex5 Output 8


# 
# connection point bcd_input
# 
add_interface bcd_input conduit end
set_interface_property bcd_input associatedClock ""
set_interface_property bcd_input associatedReset ""
set_interface_property bcd_input ENABLED true
set_interface_property bcd_input EXPORT_OF ""
set_interface_property bcd_input PORT_NAME_MAP ""
set_interface_property bcd_input CMSIS_SVD_VARIABLES ""
set_interface_property bcd_input SVD_ADDRESS_GROUP ""

add_interface_port bcd_input live_value_i bcd_input Input (NUM_DIGITS*4)

