# TCL File Generated by Component Editor 25.1
# Mon Apr 06 00:24:47 CDT 2026
# DO NOT MODIFY


# 
# spi_master "SPI Master Complete - AXI4 Lite" v1.0
#  2026.04.06.00:24:47
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module spi_master
# 
set_module_property DESCRIPTION ""
set_module_property NAME spi_master
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "SPI Master Complete - AXI4 Lite"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL axi_lite_spi
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file axi_lite_spi.sv SYSTEM_VERILOG PATH ../rtl/peripherals/spi/axi_lite_spi.sv TOP_LEVEL_FILE
add_fileset_file spi_regs.sv SYSTEM_VERILOG PATH ../rtl/peripherals/spi/regs/spi_regs.sv
add_fileset_file clk_valid.v VERILOG PATH ../rtl/peripherals/spi/vendor/opencores_verilog_spi/trunk/clk_valid.v
add_fileset_file spi_master.v VERILOG PATH ../rtl/peripherals/spi/vendor/opencores_verilog_spi/trunk/spi_master.v


# 
# parameters
# 
add_parameter AXIL_ADDR_W INTEGER 12 ""
set_parameter_property AXIL_ADDR_W DEFAULT_VALUE 12
set_parameter_property AXIL_ADDR_W DISPLAY_NAME AXIL_ADDR_W
set_parameter_property AXIL_ADDR_W WIDTH ""
set_parameter_property AXIL_ADDR_W TYPE INTEGER
set_parameter_property AXIL_ADDR_W UNITS None
set_parameter_property AXIL_ADDR_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXIL_ADDR_W DESCRIPTION ""
set_parameter_property AXIL_ADDR_W HDL_PARAMETER true
add_parameter DATA_W INTEGER 32 ""
set_parameter_property DATA_W DEFAULT_VALUE 32
set_parameter_property DATA_W DISPLAY_NAME DATA_W
set_parameter_property DATA_W WIDTH ""
set_parameter_property DATA_W TYPE INTEGER
set_parameter_property DATA_W UNITS None
set_parameter_property DATA_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_W DESCRIPTION ""
set_parameter_property DATA_W HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset start
set_interface_property reset associatedClock clock
set_interface_property reset associatedDirectReset ""
set_interface_property reset associatedResetSinks ""
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Output 1


# 
# connection point s_axil
# 
add_interface s_axil axi4lite end
set_interface_property s_axil associatedClock clock
set_interface_property s_axil associatedReset reset
set_interface_property s_axil readAcceptanceCapability 1
set_interface_property s_axil writeAcceptanceCapability 1
set_interface_property s_axil combinedAcceptanceCapability 1
set_interface_property s_axil readDataReorderingDepth 1
set_interface_property s_axil bridgesToMaster ""
set_interface_property s_axil ENABLED true
set_interface_property s_axil EXPORT_OF ""
set_interface_property s_axil PORT_NAME_MAP ""
set_interface_property s_axil CMSIS_SVD_VARIABLES ""
set_interface_property s_axil SVD_ADDRESS_GROUP ""

